tasks:
  - init: docker-compose pull --include-deps mariadb:10.7 redis:6.2-alpine \
      appwrite/influxdb:1.4.0 appwrite/telegraf:1.3.0 appwrite/mailcatcher:1.0.0 \
      appwrite/requestcatcher:1.0.0 adminer
    command: |
      docker-compose up -d
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
