tasks:
  - init: docker-compose pull &&
      docker-compose build
    command: |
      docker-compose up -d      
  - init: docker-compose pull &&docker run --rm --interactive --tty \
      --volume $PWD:/app \
      composer update --ignore-platform-reqs \
      --optimize-autoloader --no-plugins --no-scripts --prefer-dist

ports:
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
