image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker-compose pull &&
      docker-compose build &&
      docker run --rm --interactive --tty --volume $PWD:/app composer update --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts --prefer-dist
    command: |
      docker-compose up -d

ports:
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
