language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - eldad@appwrite.io

services:
- docker

before_install:
- composer update --ignore-platform-reqs --optimize-autoloader --no-dev --no-plugins --no-scripts

install:
- docker-compose up -d -f tests/resources/docker-compose.yml
- sleep 60

script:
- php -v
- ls storage
- ls tests/reosurces/storage