language: php

php:
  - '7.3'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

# cache:
#   directories:
#   - docker_images

before_install:
- composer update --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts
- sudo service mysql stop

# before_cache:
# - docker save -o docker_images/images.tar $(docker images -a -q)

install:
- docker-compose -f tests/resources/docker-compose.yml up -d
- sleep 90

script:
- docker ps
- vendor/bin/phpunit --configuration phpunit.xml
