language: php

php:
  - '7.3'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - team@appwrite.io

services:
- docker

before_install:
- sudo service mysql stop
#- mkdir -p tests/resources/storage/db
#- cp -r tests/resources/mock/db tests/resources/storage/db

install:
- docker-compose -f tests/resources/docker-compose.yml up -d
- sleep 180

script:
- docker ps
- docker-compose -f tests/resources/docker-compose.yml exec appwrite ./vendor/bin/phpunit --configuration phpunit.xml
