language: php

php:
  - '7.3'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - eldad@appwrite.io

services:
- docker

before_install:
- composer update --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts
- sudo service mysql stop
- mkdir -p tests/resources/storage/db
- cp -r tests/resources/mock/db tests/resources/storage/db

install:
- docker-compose -f tests/resources/docker-compose.yml up -d
- sleep 60

script:
- docker ps
- vendor/bin/phpunit --configuration phpunit.xml