language: php

php:
  - '7.3'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

cache:
  directories:
  - docker_images

before_install:
- docker load -i docker_images/images.tar || true
- sudo service mysql stop

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

install:
- docker-compose -f tests/resources/docker-compose.yml up -d
- sleep 180

script:
- docker ps
- docker-compose exec -T appwrite 'ls -l'
- docker-compose exec -T appwrite 'vendor/bin/phpunit --configuration phpunit.xml'
