arch:
  - amd64

os: linux

addons:
  hostname: appwrite.test

language: minimal

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

# cache:
#   directories:
#   - docker_images

# before_install:
# - docker load -i docker_images/images.tar || true

# before_cache:
# - docker save -o docker_images/images.tar appwrite_appwrite

install:
- hostname -i
- hostname -i | awk '{print $3}'
- docker --version
- docker-compose up -d
- sleep 90

script:
- ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2
- docker ps
- docker-compose logs appwrite
- docker-compose exec appwrite doctor
- docker-compose exec appwrite vars
- docker-compose exec appwrite test
