version: '3'

services:
  appwrite:
    build: .
    restart: unless-stopped
    volumes:
    - .:/usr/share/nginx/html
    - ./docker/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./storage:/storage:rw
    ports:
    - "80:80"
    - "443:443"
    environment:
    - _APP_ENV=development
    - _APP_OPENSSL_KEY_V1=
    - _APP_REDIS_HOST=redis
    - _APP_REDIS_PORT=6379
    - _APP_DB_HOST=mariadb
    - _APP_DB_PORT=3306
    - _APP_DB_SCHEMA=appwrite
    - _APP_DB_USER=root
    - _APP_DB_PASS=password
    # - _APP_INFLUXDB_HOST=influxdb
    # - _APP_INFLUXDB_PORT=8086
    - _APP_NEWRELIC_KEY=
    - _APP_MAILGUN_KEY=
    - _APP_MAILGUN_DOMAIN=
    - _APP_SENTRY_DSN=

  mariadb:
    image: appwrite/mariadb:1.0.0 # fix issues when upgrading using: mysql_upgrade -u root -p
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./storage/db:/var/lib/mysql:rw
    ports:
    - 3306:3306/tcp

  redis:
    image: redis:5.0
    restart: unless-stopped

  clamav:
    image: appwrite/clamav:v1.0.2
    restart: unless-stopped

  influxdb:
    image: influxdb:1.6
    volumes:
    - ./storage/influxdb:/var/lib/influxdb

  #telegraf-statsd:
  #  image: registry.gitlab.com/appwrite/appwrite/telegraf-statsd