version: '3'

services:
  appwrite:
    build: .
    restart: unless-stopped
    volumes:
    - .:/usr/share/nginx/html
    - ./docker/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./storage:/storage:rw
    ports:
    - "80:80"
    - "443:443"
    environment:
    - _APP_ENV=development
    - _APP_OPENSSL_KEY_V1=
    - _APP_REDIS_HOST=redis
    - _APP_REDIS_PORT=6379
    - _APP_DB_HOST=mariadb
    - _APP_DB_PORT=3306
    - _APP_DB_SCHEMA=appwrite
    - _APP_DB_USER=root
    - _APP_DB_PASS=password
    - _APP_INFLUXDB_HOST=influxdb
    - _APP_INFLUXDB_PORT=8086
    - _APP_NEWRELIC_KEY=
    - _APP_MAILGUN_KEY=
    - _APP_MAILGUN_DOMAIN=
    - _APP_SENTRY_DSN=

  mariadb:
    image: appwrite/mariadb:1.0.0 # fix issues when upgrading using: mysql_upgrade -u root -p
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./storage/db:/var/lib/mysql:rw
    ports:
    - 3306:3306/tcp

  redis:
    image: redis:5.0
    restart: unless-stopped

  clamav:
    image: appwrite/clamav:1.0.4
    restart: unless-stopped

  influxdb:
    image: influxdb:1.6
    volumes:
      - ./storage/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  
  telegraf:
    image: appwrite/telegraf:1.0.0
    ports:
      - "8125:8125/udp"

  ############### Managment

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=redis
    ports:
    - "8081:8081"

  resque:
    image: registry.gitlab.com/appwrite/appwrite/resque-web:v1.0.2
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - RESQUE_WEB_HOST=redis
      - RESQUE_WEB_PORT=6379
      - RESQUE_WEB_HTTP_BASIC_AUTH_USER=user
      - RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD=password

  chronograf:
    image: chronograf:1.5
    volumes:
      - ./storage/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
      - AUTH_DURATION=48h
      - TOKEN_SECRET=duperduper5674829!jwt
      - GH_CLIENT_ID=d86f7145a41eacfc52cc
      - GH_CLIENT_SECRET=9e0081062367a2134e7f2ea95ba1a32d08b6c8ab
      - GH_ORGS=appwrite

  kapacitor:
    image: kapacitor:1.5
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    ports:
      - "9092:9092"