name: appwrite
version: 0.0.10
description: Appwrite is an open-source backend as a service server that abstract and simplify complex and repetitive development tasks behind a very simple to use REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-dart
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  meta: ^1.1.8
  dio: ^3.0.0
  cookie_jar: ^1.0.0
  dio_cookie_manager: ^1.0.0
