name: "Linter"

on: [pull_request]
jobs:
  tests:
    name: Linter

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Install Dependencies
      uses: php-actions/composer@v6
      run: composer install --ignore-platform-reqs --no-cache

    - name: Run Linter
      run: ./vendor/bin/phpcs -p || true
